-- Lien ket phan Content (Bai viet, Cong thuc, Video, Bai dang, Binh luan)
ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLE_CATEGORY FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);
ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLE_USER FOREIGN KEY (created_by) REFERENCES [USER](user_id);

ALTER TABLE RECIPE ADD CONSTRAINT FK_RECIPE_CATEGORY FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);
ALTER TABLE RECIPE ADD CONSTRAINT FK_RECIPE_USER FOREIGN KEY (created_by) REFERENCES [USER](user_id);

ALTER TABLE VIDEO ADD CONSTRAINT FK_VIDEO_CATEGORY FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);
ALTER TABLE VIDEO ADD CONSTRAINT FK_VIDEO_USER FOREIGN KEY (created_by) REFERENCES [USER](user_id);

ALTER TABLE POST ADD CONSTRAINT FK_POST_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);
ALTER TABLE POST ADD CONSTRAINT FK_POST_CATEGORY FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id);

ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_POST FOREIGN KEY (post_id) REFERENCES POST(post_id);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);

ALTER TABLE POST_INTERACTION ADD CONSTRAINT FK_INTERACTION_POST FOREIGN KEY (post_id) REFERENCES POST(post_id);
ALTER TABLE POST_INTERACTION ADD CONSTRAINT FK_INTERACTION_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);

ALTER TABLE RECIPE_INGREDIENT ADD CONSTRAINT FK_RI_RECIPE FOREIGN KEY (recipe_id) REFERENCES RECIPE(recipe_id);
ALTER TABLE RECIPE_INGREDIENT ADD CONSTRAINT FK_RI_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES INGREDIENT(ingredient_id);

ALTER TABLE USER_ALLERGY ADD CONSTRAINT FK_UA_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);
ALTER TABLE USER_ALLERGY ADD CONSTRAINT FK_UA_ALLERGY FOREIGN KEY (allergy_id) REFERENCES ALLERGY(allergy_id);

-- Lien ket phan BMI/AI
ALTER TABLE BMI_RECORD ADD CONSTRAINT FK_BMI_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);

ALTER TABLE MEAL_PLAN ADD CONSTRAINT FK_MP_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);
ALTER TABLE MEAL_PLAN ADD CONSTRAINT FK_MP_BMI FOREIGN KEY (bmi_id) REFERENCES BMI_RECORD(bmi_id);

ALTER TABLE MEAL_PLAN_ITEM ADD CONSTRAINT FK_MPI_MEALPLAN FOREIGN KEY (meal_plan_id) REFERENCES MEAL_PLAN(meal_plan_id);
ALTER TABLE MEAL_PLAN_ITEM ADD CONSTRAINT FK_MPI_RECIPE FOREIGN KEY (recipe_id) REFERENCES RECIPE(recipe_id);

ALTER TABLE AI_CONVERSATION ADD CONSTRAINT FK_AICONV_USER FOREIGN KEY (user_id) REFERENCES [USER](user_id);
ALTER TABLE AI_MESSAGE ADD CONSTRAINT FK_AIMSG_CONV FOREIGN KEY (conversation_id) REFERENCES AI_CONVERSATION(conversation_id);

ALTER TABLE AI_MODERATION ADD CONSTRAINT FK_AIMOD_POST FOREIGN KEY (post_id) REFERENCES POST(post_id);
ALTER TABLE AI_MODERATION ADD CONSTRAINT FK_AIMOD_VIDEO FOREIGN KEY (video_id) REFERENCES VIDEO(video_id);
ALTER TABLE AI_MODERATION ADD CONSTRAINT FK_AIMOD_REVIEWER FOREIGN KEY (reviewed_by) REFERENCES [USER](user_id);