spring.application.name=ChayBook

# MSSQL connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ChayBook_Project;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Server
server.port=8080

#JWT Configuration
jwt.secret=chaybook-local-secret-key-2026-must-be-long-enough
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# ===== GEMINI AI CONFIGURATION =====
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent

#https://aistudio.google.com/apikey link này để tạo api key, sau khi tạo xong thì copy api key vào dòng dưới
gemini.api.key= tự nhập api key