-- Add status to CATEGORY
ALTER TABLE CATEGORY
ADD status NVARCHAR(20) NOT NULL
    CONSTRAINT DF_CATEGORY_STATUS DEFAULT N'ACTIVE',
    CONSTRAINT CK_CATEGORY_STATUS
        CHECK (status IN (N'ACTIVE', N'DELETED'));
GO
-- Add status to RECIPE
ALTER TABLE RECIPE
ADD status NVARCHAR(20) NOT NULL
    CONSTRAINT DF_RECIPE_STATUS DEFAULT N'ACTIVE',
    CONSTRAINT CK_RECIPE_STATUS
        CHECK (status IN (N'ACTIVE', N'DELETED'));
GO