###
### REGISTER

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "tien_test",
    "email": "tien_test@gmail.com",
    "password": "12345678",
    "fullName": "Tien Test"
}


### LOGIN

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "votienne1605@gmail.com",
    "password": "12345678"
}

### LOGIN - ADMIN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "admin@chaybook.com",
    "password": "12345678"
}


### LOGIN - WRONG PASSWORD

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "tien_test@gmail.com",
    "password": "wrongpassword"
}


### LOGIN - EMAIL NOT FOUND

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "notfound@gmail.com",
    "password": "123456"
}

GET http://localhost:8080/api/test/protected
GET http://localhost:8080/api/test
GET http://localhost:8080/api/auth/me
POST http://localhost:8080/api/auth/logout
GET http://localhost:8080/api/admin/test
GET http://localhost:8080/api/user/test